#This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
#Install the Standalone Chrome
#Build the project
#Generates the Cucumber HTML report
#Publish report on gh-pages branch

name: CI of Automation Suite

on: 
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      standalone-chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      #run: mvn --batch-mode --update-snapshots clean verify
      run:           
          ./mvn clean verify
   
    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v2
      with:
        name: Cucumber_Report
        path: ./target/cucumber-html-reports
